name: Update copyright year(s) in license file

on:
  schedule:
    - cron: "0 0 1 * *"
  workflow_dispatch:

jobs:
  update_license:
    uses: tenshiAMD/.github/.github/workflows/update-copyright-years-in-license-file.yml@master
